repos:
    - repo: https://github.com/LiquidFun/aoc_tiles
      rev: 0.6.2
      hooks:
          - id: aoc-tiles
            args:
                 - --auto-add-tiles-to-git=amend
                 - --overwrite-year=2024
                 - --text-color=#333333
